-- create table users(
-- id serial primary key,
-- user_name varchar(120),
-- password varchar(40),
-- picture varchar(200),
-- user_id uuid NOt null default uuid_generate_v4()) with(oids=false)
-- select * from users
-- drop table users